import store from '@/store/root'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Provider } from 'react-redux'
import ProviderStore from '@/components/config/ProviderStore'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ProviderStore>
      <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
    </ProviderStore>
    
  )
}
